### ISSUE TITLE
配置文件条目不一致

### ISSUE THREAD

**Issue by eav-eav-eav** [furleywolf/Furbot-Mirai#5]
现在 Java 版本的 Config 是这样的：
```yaml
furbot:
  qq: ...
  authKey: ...
  showTail: ...
  responseFriend: ...
  responseGroup: ...
```
（不太清楚套一层 furbot 的用意 ×）
而 Kotlin 版本有点差别：
```yaml
qq: ...
authKey: ...
showTail: ...
respondFriends: ...
respondGroups: ...
```
建议统一。
